### PR TITLE
updated with ansible

### PR DESCRIPTION
**Pull request by thecloudgeek**
updated with the ansible script!

### CODE REVIEW

**Comment by neoseele** [comment]
Hey Ronak, thank you for the awesome PR! 

I noticed the entire esxi_kvm folder is missing in this PR, sounds like the PR was created against a older commit. Can you pull the HEAD of the master branch and update the PR? I will merge it as soon as that is done. 

Thanks again!

**Comment by thecloudgeek** [comment]
Yep...do we need the KVM folder? I actually didn't know what it was doing and it seemed to work without it? Should it be working without it??

**Comment by thecloudgeek** [comment]
oohhhh...is that to run locally???

**Comment by neoseele** [comment]
Yup, on a KVM host with nested virt enabled. :)

**Pull request merged**
